import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import Layout, { siteTitle } from '../components/layout';
import utilStyles from '../styles/utils.module.css';
import Date from '../components/date';

import { getSortedPostsData } from '../lib/posts';
import Script from "next/script";
import React from "react";

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}

// @ts-ignore
export default function Home({ allPostsData }) {
  // @ts-ignore
  return (
      <div className={styles.container}>
        <Head>
          <title>{siteTitle}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>
            This site was built using <a href="https://nextjs.org" target="_blank" rel="noopener noreferrer">Next.js!</a>
          </h1>

          <Layout home>
            {/* Add this <section> tag below the existing <section> tag */}
            <section className={`${utilStyles.headingMd} ${utilStyles.padding1px}`}>
              <h2 className={utilStyles.headingLg}>Blog</h2>
              <ul className={utilStyles.list}>
                {allPostsData.map(({ id, date, title }: any) => (
                    <li className={utilStyles.listItem} key={id}>
                      <Link href={`/posts/${id}`}>{title}</Link>
                      <br />
                      <small className={utilStyles.lightText}>
                        <Date dateString={date} />
                      </small>
                    </li>
                ))}
              </ul>
            </section>
          </Layout>

          <div className={styles.grid}>

            <a
                href="https://davidloor.com/"
                target="_blank"
                rel="noopener noreferrer"
                className={styles.card}
            >
              <h2>davidloor.com &rarr;</h2>
              <p>
                This is my personal website. It was built using WordPress.
              </p>
            </a>
            <a
                href="https://imerkar.com/"
                target="_blank"
                rel="noopener noreferrer"
                className={styles.card}
            >
              <h2>Imerkar.com &rarr;</h2>
              <p>
                This is a Drupal 9 site, with a react app, where we can track the crypto prices.
              </p>
            </a>
            <a
                href="https://learnenglishsounds.com/"
                target="_blank"
                rel="noopener noreferrer"
                className={styles.card}
            >
              <h2>learnenglishsounds.com &rarr;</h2>
              <p>
                This is a Drupal 9 site, built with the open social distribution. This is a site where I post youtube videos which contain information about the english sounds.
              </p>
            </a>

          </div>
        </main>


        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
  )
}
